export const ks = {
  "ref": {
    "text": {
      "fontFamily": {
        "display": "var(--ks-ref-text-fontFamily-display, TikTok Sans Display, TikTok Display, TikTok Sans Text, TikTok Text, -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol)",
        "text": "var(--ks-ref-text-fontFamily-text, TikTok Sans Text, TikTok Text, TikTok Sans Display, TikTok Display, -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol)"
      },
      "weight": {
        "regular": "var(--ks-ref-text-weight-regular, 400)",
        "medium": "var(--ks-ref-text-weight-medium, 500)"
      }
    },
    "color": {
      "white": "var(--ks-ref-color-white, white)",
      "primary": {
        "150": "var(--ks-ref-color-primary-150, #001c1b)",
        "200": "var(--ks-ref-color-primary-200, #002c2b)",
        "250": "var(--ks-ref-color-primary-250, #003b3a)",
        "300": "var(--ks-ref-color-primary-300, #004a48)",
        "350": "var(--ks-ref-color-primary-350, #005a58)",
        "400": "var(--ks-ref-color-primary-400, #006b68)",
        "450": "var(--ks-ref-color-primary-450, #017976)",
        "500": "var(--ks-ref-color-primary-500, #009995)",
        "550": "var(--ks-ref-color-primary-550, #00a5a0)",
        "650": "var(--ks-ref-color-primary-650, #31bdb8)",
        "750": "var(--ks-ref-color-primary-750, #6fd5d1)",
        "850": "var(--ks-ref-color-primary-850, #9ee1dd)",
        "900": "var(--ks-ref-color-primary-900, #c3e9e7)",
        "950": "var(--ks-ref-color-primary-950, #d7f2f0)",
        "975": "var(--ks-ref-color-primary-975, #e8fbf9)",
        "995": "var(--ks-ref-color-primary-995, #f2fdfc)",
        "1000": "var(--ks-ref-color-primary-1000, white)"
      },
      "support": {
        "150": "var(--ks-ref-color-support-150, #15142b)",
        "200": "var(--ks-ref-color-support-200, #221f4b)",
        "250": "var(--ks-ref-color-support-250, #2e286a)",
        "300": "var(--ks-ref-color-support-300, #3a3086)",
        "350": "var(--ks-ref-color-support-350, #473aa5)",
        "400": "var(--ks-ref-color-support-400, #5548bd)",
        "450": "var(--ks-ref-color-support-450, #665cd6)",
        "500": "var(--ks-ref-color-support-500, #8078f6)",
        "550": "var(--ks-ref-color-support-550, #8987f6)",
        "650": "var(--ks-ref-color-support-650, #a1a1fa)",
        "750": "var(--ks-ref-color-support-750, #babdff)",
        "850": "var(--ks-ref-color-support-850, #cdcfff)",
        "900": "var(--ks-ref-color-support-900, #dcdeff)",
        "950": "var(--ks-ref-color-support-950, #e9ebff)",
        "975": "var(--ks-ref-color-support-975, #f5f4ff)",
        "995": "var(--ks-ref-color-support-995, #fbfaff)",
        "1000": "var(--ks-ref-color-support-1000, white)"
      },
      "neutral": {
        "150": "var(--ks-ref-color-neutral-150, #121415)",
        "200": "var(--ks-ref-color-neutral-200, #262627)",
        "250": "var(--ks-ref-color-neutral-250, #343435)",
        "300": "var(--ks-ref-color-neutral-300, #404142)",
        "350": "var(--ks-ref-color-neutral-350, #4f5051)",
        "400": "var(--ks-ref-color-neutral-400, #5e5f61)",
        "450": "var(--ks-ref-color-neutral-450, #6d6e70)",
        "500": "var(--ks-ref-color-neutral-500, #87898b)",
        "550": "var(--ks-ref-color-neutral-550, #929496)",
        "650": "var(--ks-ref-color-neutral-650, #a9abac)",
        "750": "var(--ks-ref-color-neutral-750, #c3c4c5)",
        "850": "var(--ks-ref-color-neutral-850, #d3d4d5)",
        "900": "var(--ks-ref-color-neutral-900, #e1e1e2)",
        "950": "var(--ks-ref-color-neutral-950, #ececed)",
        "975": "var(--ks-ref-color-neutral-975, #f2f3f3)",
        "995": "var(--ks-ref-color-neutral-995, #f8f8f9)",
        "1000": "var(--ks-ref-color-neutral-1000, white)"
      },
      "error": {
        "150": "var(--ks-ref-color-error-150, #2b0e07)",
        "200": "var(--ks-ref-color-error-200, #4e0c0b)",
        "250": "var(--ks-ref-color-error-250, #680e13)",
        "300": "var(--ks-ref-color-error-300, #801118)",
        "350": "var(--ks-ref-color-error-350, #9b1720)",
        "400": "var(--ks-ref-color-error-400, #b51d27)",
        "450": "var(--ks-ref-color-error-450, #ca242e)",
        "500": "var(--ks-ref-color-error-500, #ef504b)",
        "550": "var(--ks-ref-color-error-550, #f4655b)",
        "650": "var(--ks-ref-color-error-650, #f78a7e)",
        "750": "var(--ks-ref-color-error-750, #ffafa3)",
        "850": "var(--ks-ref-color-error-850, #ffc6bd)",
        "900": "var(--ks-ref-color-error-900, #ffd8d2)",
        "950": "var(--ks-ref-color-error-950, #ffe7e3)",
        "975": "var(--ks-ref-color-error-975, #fff2f0)",
        "995": "var(--ks-ref-color-error-995, #fff9f8)",
        "1000": "var(--ks-ref-color-error-1000, white)"
      },
      "warning": {
        "150": "var(--ks-ref-color-warning-150, #201507)",
        "200": "var(--ks-ref-color-warning-200, #342209)",
        "250": "var(--ks-ref-color-warning-250, #462f08)",
        "300": "var(--ks-ref-color-warning-300, #573b09)",
        "350": "var(--ks-ref-color-warning-350, #68490b)",
        "400": "var(--ks-ref-color-warning-400, #7a580e)",
        "450": "var(--ks-ref-color-warning-450, #8d670b)",
        "500": "var(--ks-ref-color-warning-500, #ad821a)",
        "550": "var(--ks-ref-color-warning-550, #ba8b04)",
        "650": "var(--ks-ref-color-warning-650, #d2a106)",
        "750": "var(--ks-ref-color-warning-750, #f0c133)",
        "850": "var(--ks-ref-color-warning-850, #fad253)",
        "900": "var(--ks-ref-color-warning-900, #fbde89)",
        "950": "var(--ks-ref-color-warning-950, #fbebbc)",
        "975": "var(--ks-ref-color-warning-975, #fdf5da)",
        "995": "var(--ks-ref-color-warning-995, #fffbec)",
        "1000": "var(--ks-ref-color-warning-1000, white)"
      },
      "success": {
        "150": "var(--ks-ref-color-success-150, #051c06)",
        "200": "var(--ks-ref-color-success-200, #052d0f)",
        "250": "var(--ks-ref-color-success-250, #033d15)",
        "300": "var(--ks-ref-color-success-300, #034c1c)",
        "350": "var(--ks-ref-color-success-350, #035d23)",
        "400": "var(--ks-ref-color-success-400, #056e2b)",
        "450": "var(--ks-ref-color-success-450, #057e33)",
        "500": "var(--ks-ref-color-success-500, #2a9c49)",
        "550": "var(--ks-ref-color-success-550, #35a752)",
        "650": "var(--ks-ref-color-success-650, #55bd69)",
        "750": "var(--ks-ref-color-success-750, #7ad889)",
        "850": "var(--ks-ref-color-success-850, #99e4a2)",
        "900": "var(--ks-ref-color-success-900, #baecbf)",
        "950": "var(--ks-ref-color-success-950, #ddf9df)",
        "975": "var(--ks-ref-color-success-975, #e7fde8)",
        "995": "var(--ks-ref-color-success-995, #effff0)",
        "1000": "var(--ks-ref-color-success-1000, white)"
      },
      "indigo": {
        "150": "var(--ks-ref-color-indigo-150, #0F162D)",
        "200": "var(--ks-ref-color-indigo-200, #1C2541)",
        "250": "var(--ks-ref-color-indigo-250, #263157)",
        "300": "var(--ks-ref-color-indigo-300, #2F3D6F)",
        "350": "var(--ks-ref-color-indigo-350, #37498D)",
        "400": "var(--ks-ref-color-indigo-400, #4156A8)",
        "450": "var(--ks-ref-color-indigo-450, #4D65C3)",
        "500": "var(--ks-ref-color-indigo-500, #6480E6)",
        "550": "var(--ks-ref-color-indigo-550, #728DEC)",
        "650": "var(--ks-ref-color-indigo-650, #95AEFE)",
        "750": "var(--ks-ref-color-indigo-750, #AAC4FC)",
        "850": "var(--ks-ref-color-indigo-850, #C2D5FB)",
        "900": "var(--ks-ref-color-indigo-900, #D6E2FA)",
        "950": "var(--ks-ref-color-indigo-950, #E3EEFF)",
        "975": "var(--ks-ref-color-indigo-975, #F0F6FF)",
        "995": "var(--ks-ref-color-indigo-995, #F8FBFF)"
      },
      "blue": {
        "150": "var(--ks-ref-color-blue-150, #001A2B)",
        "200": "var(--ks-ref-color-blue-200, #012B3E)",
        "250": "var(--ks-ref-color-blue-250, #003953)",
        "300": "var(--ks-ref-color-blue-300, #044765)",
        "350": "var(--ks-ref-color-blue-350, #00577D)",
        "400": "var(--ks-ref-color-blue-400, #006697)",
        "450": "var(--ks-ref-color-blue-450, #0074A6)",
        "500": "var(--ks-ref-color-blue-500, #2D94C8)",
        "550": "var(--ks-ref-color-blue-550, #3D9FD4)",
        "650": "var(--ks-ref-color-blue-650, #7CC0ED)",
        "750": "var(--ks-ref-color-blue-750, #98CCF0)",
        "850": "var(--ks-ref-color-blue-850, #B0DBFA)",
        "900": "var(--ks-ref-color-blue-900, #CAE6FC)",
        "950": "var(--ks-ref-color-blue-950, #E3F3FF)",
        "975": "var(--ks-ref-color-blue-975, #EDF7FE)",
        "995": "var(--ks-ref-color-blue-995, #F7FBFF)"
      },
      "pink": {
        "150": "var(--ks-ref-color-pink-150, #20111F)",
        "200": "var(--ks-ref-color-pink-200, #331E31)",
        "250": "var(--ks-ref-color-pink-250, #442942)",
        "300": "var(--ks-ref-color-pink-300, #533451)",
        "350": "var(--ks-ref-color-pink-350, #664163)",
        "400": "var(--ks-ref-color-pink-400, #784D75)",
        "450": "var(--ks-ref-color-pink-450, #8B5A88)",
        "500": "var(--ks-ref-color-pink-500, #AA72A7)",
        "550": "var(--ks-ref-color-pink-550, #B87BB4)",
        "650": "var(--ks-ref-color-pink-650, #D19DCD)",
        "750": "var(--ks-ref-color-pink-750, #DAB6D7)",
        "850": "var(--ks-ref-color-pink-850, #E3CBE1)",
        "900": "var(--ks-ref-color-pink-900, #EBDCE9)",
        "950": "var(--ks-ref-color-pink-950, #F2EAF1)",
        "975": "var(--ks-ref-color-pink-975, #F7F4F7)",
        "995": "var(--ks-ref-color-pink-995, #FCFAFB)"
      },
      "orange": {
        "150": "var(--ks-ref-color-orange-150, #280F03)",
        "200": "var(--ks-ref-color-orange-200, #3B1E0E)",
        "250": "var(--ks-ref-color-orange-250, #4F2913)",
        "300": "var(--ks-ref-color-orange-300, #623216)",
        "350": "var(--ks-ref-color-orange-350, #773E1D)",
        "400": "var(--ks-ref-color-orange-400, #8D4921)",
        "450": "var(--ks-ref-color-orange-450, #A45626)",
        "500": "var(--ks-ref-color-orange-500, #C86D37)",
        "550": "var(--ks-ref-color-orange-550, #D7763E)",
        "650": "var(--ks-ref-color-orange-650, #F69C6B)",
        "750": "var(--ks-ref-color-orange-750, #F6B28E)",
        "850": "var(--ks-ref-color-orange-850, #F7C9B1)",
        "900": "var(--ks-ref-color-orange-900, #F8DBCC)",
        "950": "var(--ks-ref-color-orange-950, #F9E9E1)",
        "975": "var(--ks-ref-color-orange-975, #FBF3EF)",
        "995": "var(--ks-ref-color-orange-995, #FDFAF8)"
      }
    }
  },
  "transition": {
    "easing": {
      "standardIn": "var(--ks-transition-easing-standardIn, cubic-bezier(0.32, 0, 0.67, 0))",
      "standardOut": "var(--ks-transition-easing-standardOut, cubic-bezier(0.33, 1, 0.68, 1))",
      "standardInOut": "var(--ks-transition-easing-standardInOut, cubic-bezier(0.4, 0, 0.2, 1))"
    }
  },
  "spacing": {
    "0": "var(--ks-spacing-0, 0)",
    "50": "var(--ks-spacing-50, 2px)",
    "100": "var(--ks-spacing-100, 4px)",
    "150": "var(--ks-spacing-150, 6px)",
    "200": "var(--ks-spacing-200, 8px)",
    "250": "var(--ks-spacing-250, 10px)",
    "300": "var(--ks-spacing-300, 12px)",
    "400": "var(--ks-spacing-400, 16px)",
    "500": "var(--ks-spacing-500, 20px)",
    "600": "var(--ks-spacing-600, 24px)",
    "700": "var(--ks-spacing-700, 28px)",
    "800": "var(--ks-spacing-800, 32px)",
    "900": "var(--ks-spacing-900, 36px)",
    "1000": "var(--ks-spacing-1000, 40px)",
    "1200": "var(--ks-spacing-1200, 48px)",
    "1400": "var(--ks-spacing-1400, 56px)",
    "1600": "var(--ks-spacing-1600, 64px)",
    "1800": "var(--ks-spacing-1800, 72px)",
    "2000": "var(--ks-spacing-2000, 80px)",
    "2200": "var(--ks-spacing-2200, 88px)",
    "2400": "var(--ks-spacing-2400, 96px)"
  },
  "border": {
    "radius": {
      "sm": "var(--ks-border-radius-sm, 2px)",
      "md": "var(--ks-border-radius-md, 4px)",
      "lg": "var(--ks-border-radius-lg, 6px)",
      "xl": "var(--ks-border-radius-xl, 8px)",
      "full": "var(--ks-border-radius-full, 9999px)",
      "innerMd": "var(--ks-border-radius-innerMd, 3px)"
    }
  },
  "elevation": {
    "shadow": {
      "level1": "var(--ks-elevation-shadow-level1, 0 2px 8px 0 rgba(0, 0, 0, 0.12))",
      "level2": "var(--ks-elevation-shadow-level2, 0 0 12px 0 rgba(0, 0, 0, 0.12))",
      "level3": "var(--ks-elevation-shadow-level3, 0 8px 20px 0 rgba(0, 0, 0, 0.12))",
      "level4": "var(--ks-elevation-shadow-level4, 0 8px 28px 0 rgba(0, 0, 0, 0.12))"
    }
  },
  "text": {
    "headlineLg": {
      "fontSize": "var(--ks-text-headlineLg-fontSize, 32px)",
      "lineHeight": "var(--ks-text-headlineLg-lineHeight, 40px)",
      "fontWeight": "var(--ks-text-headlineLg-fontWeight, 500)",
      "letterSpacing": "var(--ks-text-headlineLg-letterSpacing, 0)",
      "fontFamily": "var(--ks-text-headlineLg-fontFamily, TikTok Sans Display, TikTok Display, TikTok Sans Text, TikTok Text, -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol)"
    },
    "headlineMd": {
      "fontSize": "var(--ks-text-headlineMd-fontSize, 24px)",
      "lineHeight": "var(--ks-text-headlineMd-lineHeight, 32px)",
      "fontWeight": "var(--ks-text-headlineMd-fontWeight, 500)",
      "letterSpacing": "var(--ks-text-headlineMd-letterSpacing, 0.24px)",
      "fontFamily": "var(--ks-text-headlineMd-fontFamily, TikTok Sans Display, TikTok Display, TikTok Sans Text, TikTok Text, -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol)"
    },
    "headlineSm": {
      "fontSize": "var(--ks-text-headlineSm-fontSize, 20px)",
      "lineHeight": "var(--ks-text-headlineSm-lineHeight, 28px)",
      "fontWeight": "var(--ks-text-headlineSm-fontWeight, 500)",
      "letterSpacing": "var(--ks-text-headlineSm-letterSpacing, 0.3px)",
      "fontFamily": "var(--ks-text-headlineSm-fontFamily, TikTok Sans Display, TikTok Display, TikTok Sans Text, TikTok Text, -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol)"
    },
    "titleLg": {
      "fontSize": "var(--ks-text-titleLg-fontSize, 18px)",
      "lineHeight": "var(--ks-text-titleLg-lineHeight, 26px)",
      "fontWeight": "var(--ks-text-titleLg-fontWeight, 500)",
      "letterSpacing": "var(--ks-text-titleLg-letterSpacing, 0.03px)",
      "fontFamily": "var(--ks-text-titleLg-fontFamily, TikTok Sans Text, TikTok Text, TikTok Sans Display, TikTok Display, -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol)"
    },
    "titleMd": {
      "fontSize": "var(--ks-text-titleMd-fontSize, 16px)",
      "lineHeight": "var(--ks-text-titleMd-lineHeight, 24px)",
      "fontWeight": "var(--ks-text-titleMd-fontWeight, 500)",
      "letterSpacing": "var(--ks-text-titleMd-letterSpacing, 0.03px)",
      "fontFamily": "var(--ks-text-titleMd-fontFamily, TikTok Sans Text, TikTok Text, TikTok Sans Display, TikTok Display, -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol)"
    },
    "titleSm": {
      "fontSize": "var(--ks-text-titleSm-fontSize, 14px)",
      "lineHeight": "var(--ks-text-titleSm-lineHeight, 20px)",
      "fontWeight": "var(--ks-text-titleSm-fontWeight, 500)",
      "letterSpacing": "var(--ks-text-titleSm-letterSpacing, 0.09px)",
      "fontFamily": "var(--ks-text-titleSm-fontFamily, TikTok Sans Text, TikTok Text, TikTok Sans Display, TikTok Display, -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol)"
    },
    "bodyLg": {
      "fontSize": "var(--ks-text-bodyLg-fontSize, 18px)",
      "lineHeight": "var(--ks-text-bodyLg-lineHeight, 26px)",
      "fontWeight": "var(--ks-text-bodyLg-fontWeight, 400)",
      "letterSpacing": "var(--ks-text-bodyLg-letterSpacing, 0.03px)",
      "fontFamily": "var(--ks-text-bodyLg-fontFamily, TikTok Sans Text, TikTok Text, TikTok Sans Display, TikTok Display, -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol)"
    },
    "bodyMd": {
      "fontSize": "var(--ks-text-bodyMd-fontSize, 16px)",
      "lineHeight": "var(--ks-text-bodyMd-lineHeight, 24px)",
      "fontWeight": "var(--ks-text-bodyMd-fontWeight, 400)",
      "letterSpacing": "var(--ks-text-bodyMd-letterSpacing, 0.03px)",
      "fontFamily": "var(--ks-text-bodyMd-fontFamily, TikTok Sans Text, TikTok Text, TikTok Sans Display, TikTok Display, -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol)"
    },
    "bodySm": {
      "fontSize": "var(--ks-text-bodySm-fontSize, 14px)",
      "lineHeight": "var(--ks-text-bodySm-lineHeight, 20px)",
      "fontWeight": "var(--ks-text-bodySm-fontWeight, 400)",
      "letterSpacing": "var(--ks-text-bodySm-letterSpacing, 0.09px)",
      "fontFamily": "var(--ks-text-bodySm-fontFamily, TikTok Sans Text, TikTok Text, TikTok Sans Display, TikTok Display, -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol)"
    },
    "labelLg": {
      "fontSize": "var(--ks-text-labelLg-fontSize, 14px)",
      "lineHeight": "var(--ks-text-labelLg-lineHeight, 20px)",
      "fontWeight": "var(--ks-text-labelLg-fontWeight, 500)",
      "letterSpacing": "var(--ks-text-labelLg-letterSpacing, 0.09px)",
      "fontFamily": "var(--ks-text-labelLg-fontFamily, TikTok Sans Text, TikTok Text, TikTok Sans Display, TikTok Display, -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol)"
    },
    "labelMd": {
      "fontSize": "var(--ks-text-labelMd-fontSize, 12px)",
      "lineHeight": "var(--ks-text-labelMd-lineHeight, 16px)",
      "fontWeight": "var(--ks-text-labelMd-fontWeight, 500)",
      "letterSpacing": "var(--ks-text-labelMd-letterSpacing, 0.16px)",
      "fontFamily": "var(--ks-text-labelMd-fontFamily, TikTok Sans Text, TikTok Text, TikTok Sans Display, TikTok Display, -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol)"
    },
    "labelSm": {
      "fontSize": "var(--ks-text-labelSm-fontSize, 12px)",
      "lineHeight": "var(--ks-text-labelSm-lineHeight, 16px)",
      "fontWeight": "var(--ks-text-labelSm-fontWeight, 400)",
      "letterSpacing": "var(--ks-text-labelSm-letterSpacing, 0.16px)",
      "fontFamily": "var(--ks-text-labelSm-fontFamily, TikTok Sans Text, TikTok Text, TikTok Sans Display, TikTok Display, -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol)"
    }
  },
  "color": {
    "primary": {
      "fill": "var(--ks-color-primary-fill, #009995)",
      "fillHover": "var(--ks-color-primary-fillHover, #008581)",
      "fillActive": "var(--ks-color-primary-fillActive, #007875)",
      "fillDisabled": "var(--ks-color-primary-fillDisabled, #c3e9e7)",
      "onFill": "var(--ks-color-primary-onFill, white)",
      "fillLow": "var(--ks-color-primary-fillLow, #9ee1dd)",
      "onFillLow": "var(--ks-color-primary-onFillLow, #002c2b)",
      "onFillDisabled": "var(--ks-color-primary-onFillDisabled, white)",
      "surface": "var(--ks-color-primary-surface, white)",
      "surface1": "var(--ks-color-primary-surface1, #f2fdfc)",
      "surface1Hover": "var(--ks-color-primary-surface1Hover, #e5efee)",
      "surface1Active": "var(--ks-color-primary-surface1Active, #dee9e8)",
      "surface2": "var(--ks-color-primary-surface2, #e8fbf9)",
      "surface2Hover": "var(--ks-color-primary-surface2Hover, #dbedec)",
      "surface2Active": "var(--ks-color-primary-surface2Active, #d4e7e5)",
      "surface2Disabled": "var(--ks-color-primary-surface2Disabled, #e8fbf9)",
      "surface3": "var(--ks-color-primary-surface3, #d7f2f0)",
      "onSurface": "var(--ks-color-primary-onSurface, #017976)",
      "onSurfaceHover": "var(--ks-color-primary-onSurfaceHover, #006663)",
      "onSurfaceActive": "var(--ks-color-primary-onSurfaceActive, #005a57)",
      "onSurfaceDisabled": "var(--ks-color-primary-onSurfaceDisabled, #a9abac)",
      "transparentFill": "var(--ks-color-primary-transparentFill, #01797600)",
      "transparentFillHover": "var(--ks-color-primary-transparentFillHover, #00666312)",
      "transparentFillActive": "var(--ks-color-primary-transparentFillActive, #005a5724)",
      "transparentFillDisabled": "var(--ks-color-primary-transparentFillDisabled, #01797600)"
    },
    "support": {
      "fill": "var(--ks-color-support-fill, #8078f6)",
      "fillLow": "var(--ks-color-support-fillLow, #cdcfff)",
      "fillHover": "var(--ks-color-support-fillHover, #6f65e1)",
      "fillActive": "var(--ks-color-support-fillActive, #6459d4)",
      "fillDisabled": "var(--ks-color-support-fillDisabled, #dcdeff)",
      "onFill": "var(--ks-color-support-onFill, white)",
      "onFillLow": "var(--ks-color-support-onFillLow, #221f4b)",
      "onFillDisabled": "var(--ks-color-support-onFillDisabled, white)",
      "surface": "var(--ks-color-support-surface, white)",
      "surface1": "var(--ks-color-support-surface1, #fbfaff)",
      "surface2": "var(--ks-color-support-surface2, #f5f4ff)",
      "surface2Hover": "var(--ks-color-support-surface2Hover, #e7e6f2)",
      "surface2Active": "var(--ks-color-support-surface2Active, #e1e0eb)",
      "surface3": "var(--ks-color-support-surface3, #e9ebff)",
      "onSurface": "var(--ks-color-support-onSurface, #665cd6)",
      "onSurfaceHover": "var(--ks-color-support-onSurfaceHover, #5749c2)",
      "onSurfaceActive": "var(--ks-color-support-onSurfaceActive, #4d3cb5)",
      "onSurfaceDisabled": "var(--ks-color-support-onSurfaceDisabled, #a1a1fa)"
    },
    "neutral": {
      "fill": "var(--ks-color-neutral-fill, #87898b)",
      "fillHover": "var(--ks-color-neutral-fillHover, #767779)",
      "fillActive": "var(--ks-color-neutral-fillActive, #6a6c6e)",
      "fillDisabled": "var(--ks-color-neutral-fillDisabled, #e1e1e2)",
      "onFill": "var(--ks-color-neutral-onFill, white)",
      "onFillDisabled": "var(--ks-color-neutral-onFillDisabled, white)",
      "fillHigh": "var(--ks-color-neutral-fillHigh, #262627)",
      "fillHighHover": "var(--ks-color-neutral-fillHighHover, #353536)",
      "fillHighActive": "var(--ks-color-neutral-fillHighActive, #3f4041)",
      "fillHighDisabled": "var(--ks-color-neutral-fillHighDisabled, #e1e1e2)",
      "fillMedHigh": "var(--ks-color-neutral-fillMedHigh, #404142)",
      "fillMedHighHover": "var(--ks-color-neutral-fillMedHighHover, #505152)",
      "fillMedHighActive": "var(--ks-color-neutral-fillMedHighActive, #5b5c5d)",
      "fillMedHighDisabled": "var(--ks-color-neutral-fillMedHighDisabled, #e1e1e2)",
      "fillLow": "var(--ks-color-neutral-fillLow, #d3d4d5)",
      "fillLowHover": "var(--ks-color-neutral-fillLowHover, #c0c1c1)",
      "fillLowActive": "var(--ks-color-neutral-fillLowActive, #b3b4b5)",
      "fillLowDisabled": "var(--ks-color-neutral-fillLowDisabled, #e1e1e2)",
      "fillLowInverse": "var(--ks-color-neutral-fillLowInverse, #ececed)",
      "fillLowInverseHover": "var(--ks-color-neutral-fillLowInverseHover, #f2f3f3)",
      "fillLowInverseActive": "var(--ks-color-neutral-fillLowInverseActive, #f8f8f9)",
      "onFillLow": "var(--ks-color-neutral-onFillLow, #262627)",
      "surface": "var(--ks-color-neutral-surface, white)",
      "surfaceHover": "var(--ks-color-neutral-surfaceHover, #f1f2f2)",
      "surfaceActive": "var(--ks-color-neutral-surfaceActive, #ebebeb)",
      "surface1": "var(--ks-color-neutral-surface1, #f8f8f9)",
      "surface1Hover": "var(--ks-color-neutral-surface1Hover, #ebebeb)",
      "surface1Active": "var(--ks-color-neutral-surface1Active, #e4e4e5)",
      "surface2": "var(--ks-color-neutral-surface2, #f2f3f3)",
      "surface2Hover": "var(--ks-color-neutral-surface2Hover, #e5e5e6)",
      "surface2Active": "var(--ks-color-neutral-surface2Active, #dfdfdf)",
      "surface2Disabled": "var(--ks-color-neutral-surface2Disabled, #f8f8f9)",
      "surface3": "var(--ks-color-neutral-surface3, #ececed)",
      "surface3Hover": "var(--ks-color-neutral-surface3Hover, #dfdfe0)",
      "surface3Active": "var(--ks-color-neutral-surface3Active, #d8d9d9)",
      "surface3Disabled": "var(--ks-color-neutral-surface3Disabled, #f8f8f9)",
      "onSurface": "var(--ks-color-neutral-onSurface, #6d6e70)",
      "onSurfaceHover": "var(--ks-color-neutral-onSurfaceHover, #5c5d5f)",
      "onSurfaceActive": "var(--ks-color-neutral-onSurfaceActive, #515254)",
      "onSurfaceDisabled": "var(--ks-color-neutral-onSurfaceDisabled, #a9abac)",
      "highOnSurface": "var(--ks-color-neutral-highOnSurface, #121415)",
      "highOnSurfaceHover": "var(--ks-color-neutral-highOnSurfaceHover, #242728)",
      "highOnSurfaceActive": "var(--ks-color-neutral-highOnSurfaceActive, #2e3132)",
      "highOnSurfaceDisabled": "var(--ks-color-neutral-highOnSurfaceDisabled, #a9abac)",
      "lowOnSurface": "var(--ks-color-neutral-lowOnSurface, #87898B)",
      "lowOnSurfaceHover": "var(--ks-color-neutral-lowOnSurfaceHover, #757779)",
      "lowOnSurfaceActive": "var(--ks-color-neutral-lowOnSurfaceActive, 6A6C6E)",
      "lowOnSurfaceDisabled": "var(--ks-color-neutral-lowOnSurfaceDisabled, #a9abac)",
      "overlay": "var(--ks-color-neutral-overlay, #26262780)",
      "overlayHigh": "var(--ks-color-neutral-overlayHigh, #262627b3)",
      "overlayHighDisabled": "var(--ks-color-neutral-overlayHighDisabled, #e1e1e2)",
      "overlayLow": "var(--ks-color-neutral-overlayLow, #26262726)",
      "overlayLowDisabled": "var(--ks-color-neutral-overlayLowDisabled, #12141512)",
      "transparentFill": "var(--ks-color-neutral-transparentFill, #12141500)",
      "transparentFillHover": "var(--ks-color-neutral-transparentFillHover, #12141512)",
      "transparentFillActive": "var(--ks-color-neutral-transparentFillActive, #12141524)",
      "transparentFillDisabled": "var(--ks-color-neutral-transparentFillDisabled, #12141500)"
    },
    "error": {
      "fill": "var(--ks-color-error-fill, #ef504b)",
      "fillHover": "var(--ks-color-error-fillHover, #da3a39)",
      "fillActive": "var(--ks-color-error-fillActive, #cb2a2d)",
      "fillDisabled": "var(--ks-color-error-fillDisabled, #ffd8d2)",
      "fillMedHigh": "var(--ks-color-error-fillMedHigh, #ca242e)",
      "fillMedHighHover": "var(--ks-color-error-fillMedHighHover, #b3001c)",
      "fillMedHighActive": "var(--ks-color-error-fillMedHighActive, #9f0018)",
      "onFill": "var(--ks-color-error-onFill, white)",
      "fillLow": "var(--ks-color-error-fillLow, #ffc6bd)",
      "onFillLow": "var(--ks-color-error-onFillLow, #4e0c0b)",
      "surface": "var(--ks-color-error-surface, white)",
      "surface1": "var(--ks-color-error-surface1, #fff9f8)",
      "surface2": "var(--ks-color-error-surface2, #fff2f0)",
      "surface2Hover": "var(--ks-color-error-surface2Hover, #f2e5e2)",
      "surface2Active": "var(--ks-color-error-surface2Active, #ebdedc)",
      "surface3": "var(--ks-color-error-surface3, #ffe7e3)",
      "onSurface": "var(--ks-color-error-onSurface, #ca242e)",
      "onSurfaceHover": "var(--ks-color-error-onSurfaceHover, #b3001c)",
      "onSurfaceActive": "var(--ks-color-error-onSurfaceActive, #9f0018)"
    },
    "warning": {
      "fill": "var(--ks-color-warning-fill, #d2a106)",
      "fillHover": "var(--ks-color-warning-fillHover, #bc8f00)",
      "fillActive": "var(--ks-color-warning-fillActive, #ad8400)",
      "fillDisabled": "var(--ks-color-warning-fillDisabled, #fbde89)",
      "onFill": "var(--ks-color-warning-onFill, white)",
      "fillLow": "var(--ks-color-warning-fillLow, #fad253)",
      "onFillLow": "var(--ks-color-warning-onFillLow, #201507)",
      "surface": "var(--ks-color-warning-surface, white)",
      "surface1": "var(--ks-color-warning-surface1, #fffbec)",
      "surface2": "var(--ks-color-warning-surface2, #fdf5da)",
      "surface2Hover": "var(--ks-color-warning-surface2Hover, #f0e7cd)",
      "surface2Active": "var(--ks-color-warning-surface2Active, #e9e1c7)",
      "surface3": "var(--ks-color-warning-surface3, #fbebbc)",
      "onSurface": "var(--ks-color-warning-onSurface, #8d670b)",
      "onSurfaceHover": "var(--ks-color-warning-onSurfaceHover, #785600)",
      "onSurfaceActive": "var(--ks-color-warning-onSurfaceActive, #6a4c00)"
    },
    "success": {
      "fill": "var(--ks-color-success-fill, #2a9c49)",
      "onFill": "var(--ks-color-success-onFill, white)",
      "fillHover": "var(--ks-color-success-fillHover, #068a37)",
      "fillActive": "var(--ks-color-success-fillActive, #007c30)",
      "fillDisabled": "var(--ks-color-success-fillDisabled, #baecbf)",
      "fillLow": "var(--ks-color-success-fillLow, #99e4a2)",
      "onFillLow": "var(--ks-color-success-onFillLow, #052d0f)",
      "surface": "var(--ks-color-success-surface, white)",
      "surface1": "var(--ks-color-success-surface1, #effff0)",
      "surface2": "var(--ks-color-success-surface2, #e7fde8)",
      "surface2Hover": "var(--ks-color-success-surface2Hover, #daf0db)",
      "surface2Active": "var(--ks-color-success-surface2Active, #d3e9d5)",
      "surface3": "var(--ks-color-success-surface3, #ddf9df)",
      "onSurface": "var(--ks-color-success-onSurface, #057e33)",
      "onSurfaceHover": "var(--ks-color-success-onSurfaceHover, #006b29)",
      "onSurfaceActive": "var(--ks-color-success-onSurfaceActive, #005e23)"
    },
    "data": {
      "data1": {
        "fill": "var(--ks-color-data-data1-fill, #8987f6)",
        "fillDisabled": "var(--ks-color-data-data1-fillDisabled, #dcdeff)",
        "fillHigh": "var(--ks-color-data-data1-fillHigh, #665cd6)",
        "surface": "var(--ks-color-data-data1-surface, #a1a1fa33)",
        "surfaceDisabled": "var(--ks-color-data-data1-surfaceDisabled, #a1a1fa0d)"
      },
      "data2": {
        "fill": "var(--ks-color-data-data2-fill, #00577D)",
        "fillDisabled": "var(--ks-color-data-data2-fillDisabled, #CAE6FC)",
        "surface": "var(--ks-color-data-data2-surface, #7cc0ed33)",
        "surfaceDisabled": "var(--ks-color-data-data2-surfaceDisabled, #7cc0ed0d)"
      },
      "data3": {
        "fill": "var(--ks-color-data-data3-fill, #E3CBE1)",
        "fillDisabled": "var(--ks-color-data-data3-fillDisabled, #EBDCE9)",
        "fillMedHigh": "var(--ks-color-data-data3-fillMedHigh, #B87BB4)",
        "fillMedHighDisabled": "var(--ks-color-data-data3-fillMedHighDisabled, #EBDCE9)",
        "fillHigh": "var(--ks-color-data-data3-fillHigh, #442942)",
        "surface": "var(--ks-color-data-data3-surface, #d19dcd33)",
        "surfaceDisabled": "var(--ks-color-data-data3-surfaceDisabled, #d19dcd0d)"
      },
      "data4": {
        "fill": "var(--ks-color-data-data4-fill, #A45626)",
        "fillDisabled": "var(--ks-color-data-data4-fillDisabled, #F8DBCC)",
        "fillHigh": "var(--ks-color-data-data4-fillHigh, #623216)",
        "surface": "var(--ks-color-data-data4-surface, #f69c6b33)",
        "surfaceDisabled": "var(--ks-color-data-data4-surfaceDisabled, #f69c6b0d)"
      },
      "data5": {
        "fill": "var(--ks-color-data-data5-fill, #98CCF0)",
        "fillDisabled": "var(--ks-color-data-data5-fillDisabled, #CAE6FC)",
        "fillMedHigh": "var(--ks-color-data-data5-fillMedHigh, #3D9FD4)",
        "fillMedHighDisabled": "var(--ks-color-data-data5-fillMedHighDisabled, #CAE6FC)",
        "fillHigh": "var(--ks-color-data-data5-fillHigh, #0074A6)",
        "surface": "var(--ks-color-data-data5-surface, #b0dbfa33)",
        "surfaceDisabled": "var(--ks-color-data-data5-surfaceDisabled, #b0dbfa0d)"
      },
      "data6": {
        "fill": "var(--ks-color-data-data6-fill, #5548bd)",
        "fillDisabled": "var(--ks-color-data-data6-fillDisabled, #5548bd40)",
        "fillHigh": "var(--ks-color-data-data6-fillHigh, #473aa5)",
        "surface": "var(--ks-color-data-data6-surface, #cdcfff33)",
        "surfaceDisabled": "var(--ks-color-data-data6-surfaceDisabled, #cdcfff0d)"
      },
      "data7": {
        "fill": "var(--ks-color-data-data7-fill, #F8DBCC)",
        "fillDisabled": "var(--ks-color-data-data7-fillDisabled, #f8dbcc40)",
        "fillMedHigh": "var(--ks-color-data-data7-fillMedHigh, #D7763E)",
        "fillMedHighDisabled": "var(--ks-color-data-data7-fillMedHighDisabled, #d7763e40)",
        "fillHigh": "var(--ks-color-data-data7-fillHigh, #A45626)",
        "surface": "var(--ks-color-data-data7-surface, #f7c9b133)",
        "surfaceDisabled": "var(--ks-color-data-data7-surfaceDisabled, #f7c9b10d)"
      },
      "data8": {
        "fill": "var(--ks-color-data-data8-fill, #664163)",
        "fillDisabled": "var(--ks-color-data-data8-fillDisabled, #66416340)",
        "fillHigh": "var(--ks-color-data-data8-fillHigh, #533451)",
        "surface": "var(--ks-color-data-data8-surface, #e3cbe133)",
        "surfaceDisabled": "var(--ks-color-data-data8-surfaceDisabled, #e3cbe10d)"
      },
      "data9": {
        "fill": "var(--ks-color-data-data9-fill, #babdff)",
        "fillDisabled": "var(--ks-color-data-data9-fillDisabled, #babdff40)",
        "fillMedHigh": "var(--ks-color-data-data9-fillMedHigh, #3a3086)",
        "fillMedHighDisabled": "var(--ks-color-data-data9-fillMedHighDisabled, #3a308640)",
        "fillHigh": "var(--ks-color-data-data9-fillHigh, #221f4b)",
        "surface": "var(--ks-color-data-data9-surface, #8987f633)",
        "surfaceDisabled": "var(--ks-color-data-data9-surfaceDisabled, #8987f60d)",
        "onSurface": "var(--ks-color-data-data9-onSurface, #8987f6)"
      },
      "success": {
        "fill": "var(--ks-color-data-success-fill, #2a9c49)",
        "fillHigh": "var(--ks-color-data-success-fillHigh, #035d23)",
        "fillDisabled": "var(--ks-color-data-success-fillDisabled, #2a9c4940)",
        "surface": "var(--ks-color-data-success-surface, #55bd6933)",
        "surfaceDisabled": "var(--ks-color-data-success-surfaceDisabled, #55bd690d)"
      },
      "warning": {
        "fill": "var(--ks-color-data-warning-fill, #f0c133)",
        "fillDisabled": "var(--ks-color-data-warning-fillDisabled, #f0c13340)",
        "fillMedHigh": "var(--ks-color-data-warning-fillMedHigh, #ba8b04)",
        "fillMedHighDisabled": "var(--ks-color-data-warning-fillMedHighDisabled, #ba8b0440)",
        "surface": "var(--ks-color-data-warning-surface, #fad25333)",
        "surfaceDisabled": "var(--ks-color-data-warning-surfaceDisabled, #fad2530d)"
      },
      "error": {
        "fill": "var(--ks-color-data-error-fill, #f78a7e)",
        "fillDisabled": "var(--ks-color-data-error-fillDisabled, #f78a7e40)",
        "fillMedHigh": "var(--ks-color-data-error-fillMedHigh, #f4655b)",
        "fillMedHighDisabled": "var(--ks-color-data-error-fillMedHighDisabled, #f4655b40)",
        "surface": "var(--ks-color-data-error-surface, #f78a7e33)",
        "surfaceDisabled": "var(--ks-color-data-error-surfaceDisabled, #f78a7e0d)"
      },
      "neutral": {
        "fill": "var(--ks-color-data-neutral-fill, #728DEC)",
        "fillDisabled": "var(--ks-color-data-neutral-fillDisabled, #728dec40)",
        "fillMedHigh": "var(--ks-color-data-neutral-fillMedHigh, #5e5f61)",
        "fillMedHighDisabled": "var(--ks-color-data-neutral-fillMedHighDisabled, #5e5f6140)",
        "surface": "var(--ks-color-data-neutral-surface, #a9abac33)",
        "surfaceDisabled": "var(--ks-color-data-neutral-surfaceDisabled, #a9abac0d)"
      }
    },
    "ai": {
      "fill": "var(--ks-color-ai-fill, linear-gradient(90deg, #31bdb8 0%, #95AEFE 93.64%, #a1a1fa 186.35%))"
    }
  }
} as const;
export const darkKs = {
  "color": {
    "primary": {
      "fill": "var(--ks-color-primary-fill, #009995)",
      "fillHover": "var(--ks-color-primary-fillHover, #008581)",
      "fillActive": "var(--ks-color-primary-fillActive, #007875)",
      "fillDisabled": "var(--ks-color-primary-fillDisabled, #c3e9e7)",
      "onFill": "var(--ks-color-primary-onFill, white)",
      "fillLow": "var(--ks-color-primary-fillLow, #9ee1dd)",
      "onFillLow": "var(--ks-color-primary-onFillLow, #002c2b)",
      "onFillDisabled": "var(--ks-color-primary-onFillDisabled, white)",
      "surface": "var(--ks-color-primary-surface, white)",
      "surface1": "var(--ks-color-primary-surface1, #f2fdfc)",
      "surface1Hover": "var(--ks-color-primary-surface1Hover, #e5efee)",
      "surface1Active": "var(--ks-color-primary-surface1Active, #dee9e8)",
      "surface2": "var(--ks-color-primary-surface2, #e8fbf9)",
      "surface2Hover": "var(--ks-color-primary-surface2Hover, #dbedec)",
      "surface2Active": "var(--ks-color-primary-surface2Active, #d4e7e5)",
      "surface2Disabled": "var(--ks-color-primary-surface2Disabled, #e8fbf9)",
      "surface3": "var(--ks-color-primary-surface3, #d7f2f0)",
      "onSurface": "var(--ks-color-primary-onSurface, #017976)",
      "onSurfaceHover": "var(--ks-color-primary-onSurfaceHover, #006663)",
      "onSurfaceActive": "var(--ks-color-primary-onSurfaceActive, #005a57)",
      "onSurfaceDisabled": "var(--ks-color-primary-onSurfaceDisabled, #a9abac)",
      "transparentFill": "var(--ks-color-primary-transparentFill, #01797600)",
      "transparentFillHover": "var(--ks-color-primary-transparentFillHover, #00666312)",
      "transparentFillActive": "var(--ks-color-primary-transparentFillActive, #005a5724)",
      "transparentFillDisabled": "var(--ks-color-primary-transparentFillDisabled, #01797600)"
    },
    "support": {
      "fill": "var(--ks-color-support-fill, #8078f6)",
      "fillLow": "var(--ks-color-support-fillLow, #cdcfff)",
      "fillHover": "var(--ks-color-support-fillHover, #6f65e1)",
      "fillActive": "var(--ks-color-support-fillActive, #6459d4)",
      "fillDisabled": "var(--ks-color-support-fillDisabled, #dcdeff)",
      "onFill": "var(--ks-color-support-onFill, white)",
      "onFillLow": "var(--ks-color-support-onFillLow, #221f4b)",
      "onFillDisabled": "var(--ks-color-support-onFillDisabled, white)",
      "surface": "var(--ks-color-support-surface, white)",
      "surface1": "var(--ks-color-support-surface1, #fbfaff)",
      "surface2": "var(--ks-color-support-surface2, #f5f4ff)",
      "surface2Hover": "var(--ks-color-support-surface2Hover, #e7e6f2)",
      "surface2Active": "var(--ks-color-support-surface2Active, #e1e0eb)",
      "surface3": "var(--ks-color-support-surface3, #e9ebff)",
      "onSurface": "var(--ks-color-support-onSurface, #665cd6)",
      "onSurfaceHover": "var(--ks-color-support-onSurfaceHover, #5749c2)",
      "onSurfaceActive": "var(--ks-color-support-onSurfaceActive, #4d3cb5)",
      "onSurfaceDisabled": "var(--ks-color-support-onSurfaceDisabled, #a1a1fa)"
    },
    "neutral": {
      "fill": "var(--ks-color-neutral-fill, #87898b)",
      "fillHover": "var(--ks-color-neutral-fillHover, #767779)",
      "fillActive": "var(--ks-color-neutral-fillActive, #6a6c6e)",
      "fillDisabled": "var(--ks-color-neutral-fillDisabled, #e1e1e2)",
      "onFill": "var(--ks-color-neutral-onFill, white)",
      "onFillDisabled": "var(--ks-color-neutral-onFillDisabled, white)",
      "fillHigh": "var(--ks-color-neutral-fillHigh, #262627)",
      "fillHighHover": "var(--ks-color-neutral-fillHighHover, #353536)",
      "fillHighActive": "var(--ks-color-neutral-fillHighActive, #3f4041)",
      "fillHighDisabled": "var(--ks-color-neutral-fillHighDisabled, #e1e1e2)",
      "fillMedHigh": "var(--ks-color-neutral-fillMedHigh, #404142)",
      "fillMedHighHover": "var(--ks-color-neutral-fillMedHighHover, #505152)",
      "fillMedHighActive": "var(--ks-color-neutral-fillMedHighActive, #5b5c5d)",
      "fillMedHighDisabled": "var(--ks-color-neutral-fillMedHighDisabled, #e1e1e2)",
      "fillLow": "var(--ks-color-neutral-fillLow, #d3d4d5)",
      "fillLowHover": "var(--ks-color-neutral-fillLowHover, #c0c1c1)",
      "fillLowActive": "var(--ks-color-neutral-fillLowActive, #b3b4b5)",
      "fillLowDisabled": "var(--ks-color-neutral-fillLowDisabled, #e1e1e2)",
      "fillLowInverse": "var(--ks-color-neutral-fillLowInverse, #ececed)",
      "fillLowInverseHover": "var(--ks-color-neutral-fillLowInverseHover, #f2f3f3)",
      "fillLowInverseActive": "var(--ks-color-neutral-fillLowInverseActive, #f8f8f9)",
      "onFillLow": "var(--ks-color-neutral-onFillLow, #262627)",
      "surface": "var(--ks-color-neutral-surface, white)",
      "surfaceHover": "var(--ks-color-neutral-surfaceHover, #f1f2f2)",
      "surfaceActive": "var(--ks-color-neutral-surfaceActive, #ebebeb)",
      "surface1": "var(--ks-color-neutral-surface1, #f8f8f9)",
      "surface1Hover": "var(--ks-color-neutral-surface1Hover, #ebebeb)",
      "surface1Active": "var(--ks-color-neutral-surface1Active, #e4e4e5)",
      "surface2": "var(--ks-color-neutral-surface2, #f2f3f3)",
      "surface2Hover": "var(--ks-color-neutral-surface2Hover, #e5e5e6)",
      "surface2Active": "var(--ks-color-neutral-surface2Active, #dfdfdf)",
      "surface2Disabled": "var(--ks-color-neutral-surface2Disabled, #f8f8f9)",
      "surface3": "var(--ks-color-neutral-surface3, #ececed)",
      "surface3Hover": "var(--ks-color-neutral-surface3Hover, #dfdfe0)",
      "surface3Active": "var(--ks-color-neutral-surface3Active, #d8d9d9)",
      "surface3Disabled": "var(--ks-color-neutral-surface3Disabled, #f8f8f9)",
      "onSurface": "var(--ks-color-neutral-onSurface, #6d6e70)",
      "onSurfaceHover": "var(--ks-color-neutral-onSurfaceHover, #5c5d5f)",
      "onSurfaceActive": "var(--ks-color-neutral-onSurfaceActive, #515254)",
      "onSurfaceDisabled": "var(--ks-color-neutral-onSurfaceDisabled, #a9abac)",
      "highOnSurface": "var(--ks-color-neutral-highOnSurface, #121415)",
      "highOnSurfaceHover": "var(--ks-color-neutral-highOnSurfaceHover, #242728)",
      "highOnSurfaceActive": "var(--ks-color-neutral-highOnSurfaceActive, #2e3132)",
      "highOnSurfaceDisabled": "var(--ks-color-neutral-highOnSurfaceDisabled, #a9abac)",
      "lowOnSurface": "var(--ks-color-neutral-lowOnSurface, #87898B)",
      "lowOnSurfaceHover": "var(--ks-color-neutral-lowOnSurfaceHover, #757779)",
      "lowOnSurfaceActive": "var(--ks-color-neutral-lowOnSurfaceActive, 6A6C6E)",
      "lowOnSurfaceDisabled": "var(--ks-color-neutral-lowOnSurfaceDisabled, #a9abac)",
      "overlay": "var(--ks-color-neutral-overlay, #26262780)",
      "overlayHigh": "var(--ks-color-neutral-overlayHigh, #262627b3)",
      "overlayHighDisabled": "var(--ks-color-neutral-overlayHighDisabled, #e1e1e2)",
      "overlayLow": "var(--ks-color-neutral-overlayLow, #26262726)",
      "overlayLowDisabled": "var(--ks-color-neutral-overlayLowDisabled, #12141512)",
      "transparentFill": "var(--ks-color-neutral-transparentFill, #12141500)",
      "transparentFillHover": "var(--ks-color-neutral-transparentFillHover, #12141512)",
      "transparentFillActive": "var(--ks-color-neutral-transparentFillActive, #12141524)",
      "transparentFillDisabled": "var(--ks-color-neutral-transparentFillDisabled, #12141500)"
    },
    "error": {
      "fill": "var(--ks-color-error-fill, #ef504b)",
      "fillHover": "var(--ks-color-error-fillHover, #da3a39)",
      "fillActive": "var(--ks-color-error-fillActive, #cb2a2d)",
      "fillDisabled": "var(--ks-color-error-fillDisabled, #ffd8d2)",
      "fillMedHigh": "var(--ks-color-error-fillMedHigh, #ca242e)",
      "fillMedHighHover": "var(--ks-color-error-fillMedHighHover, #b3001c)",
      "fillMedHighActive": "var(--ks-color-error-fillMedHighActive, #9f0018)",
      "onFill": "var(--ks-color-error-onFill, white)",
      "fillLow": "var(--ks-color-error-fillLow, #ffc6bd)",
      "onFillLow": "var(--ks-color-error-onFillLow, #4e0c0b)",
      "surface": "var(--ks-color-error-surface, white)",
      "surface1": "var(--ks-color-error-surface1, #fff9f8)",
      "surface2": "var(--ks-color-error-surface2, #fff2f0)",
      "surface2Hover": "var(--ks-color-error-surface2Hover, #f2e5e2)",
      "surface2Active": "var(--ks-color-error-surface2Active, #ebdedc)",
      "surface3": "var(--ks-color-error-surface3, #ffe7e3)",
      "onSurface": "var(--ks-color-error-onSurface, #ca242e)",
      "onSurfaceHover": "var(--ks-color-error-onSurfaceHover, #b3001c)",
      "onSurfaceActive": "var(--ks-color-error-onSurfaceActive, #9f0018)"
    },
    "warning": {
      "fill": "var(--ks-color-warning-fill, #d2a106)",
      "fillHover": "var(--ks-color-warning-fillHover, #bc8f00)",
      "fillActive": "var(--ks-color-warning-fillActive, #ad8400)",
      "fillDisabled": "var(--ks-color-warning-fillDisabled, #fbde89)",
      "onFill": "var(--ks-color-warning-onFill, white)",
      "fillLow": "var(--ks-color-warning-fillLow, #fad253)",
      "onFillLow": "var(--ks-color-warning-onFillLow, #201507)",
      "surface": "var(--ks-color-warning-surface, white)",
      "surface1": "var(--ks-color-warning-surface1, #fffbec)",
      "surface2": "var(--ks-color-warning-surface2, #fdf5da)",
      "surface2Hover": "var(--ks-color-warning-surface2Hover, #f0e7cd)",
      "surface2Active": "var(--ks-color-warning-surface2Active, #e9e1c7)",
      "surface3": "var(--ks-color-warning-surface3, #fbebbc)",
      "onSurface": "var(--ks-color-warning-onSurface, #8d670b)",
      "onSurfaceHover": "var(--ks-color-warning-onSurfaceHover, #785600)",
      "onSurfaceActive": "var(--ks-color-warning-onSurfaceActive, #6a4c00)"
    },
    "success": {
      "fill": "var(--ks-color-success-fill, #2a9c49)",
      "onFill": "var(--ks-color-success-onFill, white)",
      "fillHover": "var(--ks-color-success-fillHover, #068a37)",
      "fillActive": "var(--ks-color-success-fillActive, #007c30)",
      "fillDisabled": "var(--ks-color-success-fillDisabled, #baecbf)",
      "fillLow": "var(--ks-color-success-fillLow, #99e4a2)",
      "onFillLow": "var(--ks-color-success-onFillLow, #052d0f)",
      "surface": "var(--ks-color-success-surface, white)",
      "surface1": "var(--ks-color-success-surface1, #effff0)",
      "surface2": "var(--ks-color-success-surface2, #e7fde8)",
      "surface2Hover": "var(--ks-color-success-surface2Hover, #daf0db)",
      "surface2Active": "var(--ks-color-success-surface2Active, #d3e9d5)",
      "surface3": "var(--ks-color-success-surface3, #ddf9df)",
      "onSurface": "var(--ks-color-success-onSurface, #057e33)",
      "onSurfaceHover": "var(--ks-color-success-onSurfaceHover, #006b29)",
      "onSurfaceActive": "var(--ks-color-success-onSurfaceActive, #005e23)"
    },
    "data": {
      "data1": {
        "fill": "var(--ks-color-data-data1-fill, #8987f6)",
        "fillDisabled": "var(--ks-color-data-data1-fillDisabled, #dcdeff)",
        "fillHigh": "var(--ks-color-data-data1-fillHigh, #665cd6)",
        "surface": "var(--ks-color-data-data1-surface, #a1a1fa33)",
        "surfaceDisabled": "var(--ks-color-data-data1-surfaceDisabled, #a1a1fa0d)"
      },
      "data2": {
        "fill": "var(--ks-color-data-data2-fill, #00577D)",
        "fillDisabled": "var(--ks-color-data-data2-fillDisabled, #CAE6FC)",
        "surface": "var(--ks-color-data-data2-surface, #7cc0ed33)",
        "surfaceDisabled": "var(--ks-color-data-data2-surfaceDisabled, #7cc0ed0d)"
      },
      "data3": {
        "fill": "var(--ks-color-data-data3-fill, #E3CBE1)",
        "fillDisabled": "var(--ks-color-data-data3-fillDisabled, #EBDCE9)",
        "fillMedHigh": "var(--ks-color-data-data3-fillMedHigh, #B87BB4)",
        "fillMedHighDisabled": "var(--ks-color-data-data3-fillMedHighDisabled, #EBDCE9)",
        "fillHigh": "var(--ks-color-data-data3-fillHigh, #442942)",
        "surface": "var(--ks-color-data-data3-surface, #d19dcd33)",
        "surfaceDisabled": "var(--ks-color-data-data3-surfaceDisabled, #d19dcd0d)"
      },
      "data4": {
        "fill": "var(--ks-color-data-data4-fill, #A45626)",
        "fillDisabled": "var(--ks-color-data-data4-fillDisabled, #F8DBCC)",
        "fillHigh": "var(--ks-color-data-data4-fillHigh, #623216)",
        "surface": "var(--ks-color-data-data4-surface, #f69c6b33)",
        "surfaceDisabled": "var(--ks-color-data-data4-surfaceDisabled, #f69c6b0d)"
      },
      "data5": {
        "fill": "var(--ks-color-data-data5-fill, #98CCF0)",
        "fillDisabled": "var(--ks-color-data-data5-fillDisabled, #CAE6FC)",
        "fillMedHigh": "var(--ks-color-data-data5-fillMedHigh, #3D9FD4)",
        "fillMedHighDisabled": "var(--ks-color-data-data5-fillMedHighDisabled, #CAE6FC)",
        "fillHigh": "var(--ks-color-data-data5-fillHigh, #0074A6)",
        "surface": "var(--ks-color-data-data5-surface, #b0dbfa33)",
        "surfaceDisabled": "var(--ks-color-data-data5-surfaceDisabled, #b0dbfa0d)"
      },
      "data6": {
        "fill": "var(--ks-color-data-data6-fill, #5548bd)",
        "fillDisabled": "var(--ks-color-data-data6-fillDisabled, #5548bd40)",
        "fillHigh": "var(--ks-color-data-data6-fillHigh, #473aa5)",
        "surface": "var(--ks-color-data-data6-surface, #cdcfff33)",
        "surfaceDisabled": "var(--ks-color-data-data6-surfaceDisabled, #cdcfff0d)"
      },
      "data7": {
        "fill": "var(--ks-color-data-data7-fill, #F8DBCC)",
        "fillDisabled": "var(--ks-color-data-data7-fillDisabled, #f8dbcc40)",
        "fillMedHigh": "var(--ks-color-data-data7-fillMedHigh, #D7763E)",
        "fillMedHighDisabled": "var(--ks-color-data-data7-fillMedHighDisabled, #d7763e40)",
        "fillHigh": "var(--ks-color-data-data7-fillHigh, #A45626)",
        "surface": "var(--ks-color-data-data7-surface, #f7c9b133)",
        "surfaceDisabled": "var(--ks-color-data-data7-surfaceDisabled, #f7c9b10d)"
      },
      "data8": {
        "fill": "var(--ks-color-data-data8-fill, #664163)",
        "fillDisabled": "var(--ks-color-data-data8-fillDisabled, #66416340)",
        "fillHigh": "var(--ks-color-data-data8-fillHigh, #533451)",
        "surface": "var(--ks-color-data-data8-surface, #e3cbe133)",
        "surfaceDisabled": "var(--ks-color-data-data8-surfaceDisabled, #e3cbe10d)"
      },
      "data9": {
        "fill": "var(--ks-color-data-data9-fill, #babdff)",
        "fillDisabled": "var(--ks-color-data-data9-fillDisabled, #babdff40)",
        "fillMedHigh": "var(--ks-color-data-data9-fillMedHigh, #3a3086)",
        "fillMedHighDisabled": "var(--ks-color-data-data9-fillMedHighDisabled, #3a308640)",
        "fillHigh": "var(--ks-color-data-data9-fillHigh, #221f4b)",
        "surface": "var(--ks-color-data-data9-surface, #8987f633)",
        "surfaceDisabled": "var(--ks-color-data-data9-surfaceDisabled, #8987f60d)",
        "onSurface": "var(--ks-color-data-data9-onSurface, #8987f6)"
      },
      "success": {
        "fill": "var(--ks-color-data-success-fill, #2a9c49)",
        "fillHigh": "var(--ks-color-data-success-fillHigh, #035d23)",
        "fillDisabled": "var(--ks-color-data-success-fillDisabled, #2a9c4940)",
        "surface": "var(--ks-color-data-success-surface, #55bd6933)",
        "surfaceDisabled": "var(--ks-color-data-success-surfaceDisabled, #55bd690d)"
      },
      "warning": {
        "fill": "var(--ks-color-data-warning-fill, #f0c133)",
        "fillDisabled": "var(--ks-color-data-warning-fillDisabled, #f0c13340)",
        "fillMedHigh": "var(--ks-color-data-warning-fillMedHigh, #ba8b04)",
        "fillMedHighDisabled": "var(--ks-color-data-warning-fillMedHighDisabled, #ba8b0440)",
        "surface": "var(--ks-color-data-warning-surface, #fad25333)",
        "surfaceDisabled": "var(--ks-color-data-warning-surfaceDisabled, #fad2530d)"
      },
      "error": {
        "fill": "var(--ks-color-data-error-fill, #f78a7e)",
        "fillDisabled": "var(--ks-color-data-error-fillDisabled, #f78a7e40)",
        "fillMedHigh": "var(--ks-color-data-error-fillMedHigh, #f4655b)",
        "fillMedHighDisabled": "var(--ks-color-data-error-fillMedHighDisabled, #f4655b40)",
        "surface": "var(--ks-color-data-error-surface, #f78a7e33)",
        "surfaceDisabled": "var(--ks-color-data-error-surfaceDisabled, #f78a7e0d)"
      },
      "neutral": {
        "fill": "var(--ks-color-data-neutral-fill, #728DEC)",
        "fillDisabled": "var(--ks-color-data-neutral-fillDisabled, #728dec40)",
        "fillMedHigh": "var(--ks-color-data-neutral-fillMedHigh, #5e5f61)",
        "fillMedHighDisabled": "var(--ks-color-data-neutral-fillMedHighDisabled, #5e5f6140)",
        "surface": "var(--ks-color-data-neutral-surface, #a9abac33)",
        "surfaceDisabled": "var(--ks-color-data-neutral-surfaceDisabled, #a9abac0d)"
      }
    },
    "ai": {
      "fill": "var(--ks-color-ai-fill, linear-gradient(90deg, #31bdb8 0%, #95AEFE 93.64%, #a1a1fa 186.35%))"
    }
  }
} as const;
export { getCSSVariableValue } from './getCSSVariableValue.js';

export * from './getCSSVariableValue';
